defaultTheme = "light"

title = "SwingConnection Leipzig e.V."
description = "Herzlich Willkommen bei der SwingConnection Leipzig"

# Header config
[header]

desktopMode = "fixed"

mobileMode = "auto"

[header.title]

# URL of the LOGO
logo = "images/scl_logo.png"

# title name
name = ""

# you can add extra information before the name (HTML format is supported), such as icons
pre = ""

# you can add extra information after the name (HTML format is supported), such as icons
post = ""

typeit = false

# Footer config
[footer]

enable = true
custom = ''
hugo = false
copyright = true
author = true

# Search config
[search]
enable = true

# type of search engine ["lunr", "algolia"]
type = "lunr"

# max index length of the chunked content
contentLength = 4000

# placeholder of the search bar
placeholder = ""

# max number of results length
maxResultLength = 10

# Snippet length of the result
snippetLength = 30

# HTML tag name of the highlight part in results
highlightTag = "em"

# whether to use the absolute URL based on the baseURL in search index
absoluteURL = false

# Home page config
[home]
# amount of RSS pages
rss = 10

# Home page profile
[home.profile]
enable = true

# Gravatar Email for preferred avatar in home page
gravatarEmail = ""

# URL of avatar shown in home page
avatarURL = ""

# title shown in home page (HTML format is supported)
title = ""

# subtitle shown in home page (HTML format is supported)
subtitle = ""

# whether to use typeit animation for subtitle
typeit = false

# whether to show social links
social = false

# disclaimer (HTML format is supported)
disclaimer = ""

# TypeIt config
[typeit]

# typing speed between each step (measured in milliseconds)
speed = 50

# blinking speed of the cursor (measured in milliseconds)
cursorSpeed = 1000

# character used for the cursor (HTML format is supported)
cursorChar = "|"

# cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
duration = -1

# App icon config
[app]

# optional site title override for the app when added to an iOS home screen or Android launcher
title = "SwingConnection Leipzig e.V."

# whether to omit favicon resource links
noFavicon = false

# modern SVG favicon to use in place of older style .png and .ico files
svgFavicon = ""

# Android browser theme color
themeColor = "#ffffff"

# Safari mask icon color
iconColor = "#5bbad5"

# Windows v8-10 tile color
tileColor = "#da532c"
