baseURL = 'https://hnolzen.github.io/swingconnection/'
languageCode = 'de-de'
title = 'SwingConnection Leipzig e.V.'
theme = 'LoveIt'
enableEmoji = true

# Author config
[author]
  name = "Swingconnection Leipzig e.V."

[menu]

  [[menu.main]]
	identifier = 'aktuelles'
	name = 'Aktuelles'
	url = '/aktuelles/'
	weight = 1
	
  [[menu.main]]
	identifier = 'tanzkurse'
	name = 'Tanzkurse'
	url = '/tanzkurse/'
	weight = 2

  [[menu.main]]
	identifier = 'veranstaltungen'
	name = 'Veranstaltungen'
	url = '/veranstaltungen/'
	weight = 3

  [[menu.main]]
	identifier = 'calloway'
	name = 'Tanzstudio'
	url = '/calloway/'
	weight = 4
	
  [[menu.main]]
	identifier = 'verein'
	name = 'Unser Verein'
	url = '/verein/'
	weight = 5
	
  [[menu.main]]
	identifier = 'kontakt'
	name = 'Kontakt & Impressum'
	url = '/kontakt/'
	weight = 6

[params]

  defaultTheme = "light"
  
  title = "SwingConnection Leipzig e.V."
  description = "Herzlich Willkommen bei der SwingConnection Leipzig"
  
  # Header config
  [params.header]

    desktopMode = "fixed"
    
    mobileMode = "auto"
    
    [params.header.title]
      
	  # URL of the LOGO
      logo = "scl_logo.png"
      
	  # title name
      name = "SwingConnection Leipzig e.V."
      
	  # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      
	  # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      
      typeit = true

  # Footer config
  [params.footer]
    
	enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
  
  # Search config
  [params.search]
    enable = true
    
	# type of search engine ["lunr", "algolia"]
    type = "lunr"
    
	# max index length of the chunked content
    contentLength = 4000
    
	# placeholder of the search bar
    placeholder = ""
    
	# max number of results length
    maxResultLength = 10
   
    # Snippet length of the result
    snippetLength = 30
    
	# HTML tag name of the highlight part in results
    highlightTag = "em"
    
	# whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
  
