baseURL = 'https://hnolzen.github.io/swingconnection/'
title = 'SwingConnection Leipzig e.V.'
theme = 'LoveIt'
enableEmoji = true

defaultContentLanguage = 'de'
languageCode = 'de'
languageName = "German"

# Author config
[author]
  name = "Swingconnection Leipzig e.V."

[menu]

  [[menu.main]]
	identifier = 'aktuelles'
	name = 'Aktuelles'
	url = '/aktuelles/'
	weight = 1
	
  [[menu.main]]
	identifier = 'tanzkurse'
	name = 'Tanzkurse'
	url = '/tanzkurse/'
	weight = 2

  [[menu.main]]
	identifier = 'veranstaltungen'
	name = 'Veranstaltungen'
	url = '/veranstaltungen/'
	weight = 3

  [[menu.main]]
	identifier = 'calloway'
	name = 'Tanzstudio'
	url = '/calloway/'
	weight = 4
	
  [[menu.main]]
	identifier = 'verein'
	name = 'Unser Verein'
	url = '/verein/'
	weight = 5
	
  [[menu.main]]
	identifier = 'kontakt'
	name = 'Kontakt & Impressum'
	url = '/kontakt/'
	weight = 6

[params]

  defaultTheme = "light"
  
  title = "SwingConnection Leipzig e.V."
  description = "Herzlich Willkommen bei der SwingConnection Leipzig"
  
  # Header config
  [params.header]

    desktopMode = "fixed"
    
    mobileMode = "auto"
    
    [params.header.title]
      
	  # URL of the LOGO
      logo = "images/scl_logo.png"
      
	  # title name
      name = "SwingConnection Leipzig e.V."
      
	  # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      
	  # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      
      typeit = false

  # Footer config
  [params.footer]
    
	enable = true
    custom = ''
    hugo = false
    copyright = true
    author = true
  
  # Search config
  [params.search]
    enable = true
    
	# type of search engine ["lunr", "algolia"]
    type = "lunr"
    
	# max index length of the chunked content
    contentLength = 4000
    
	# placeholder of the search bar
    placeholder = ""
    
	# max number of results length
    maxResultLength = 10
   
    # Snippet length of the result
    snippetLength = 30
    
	# HTML tag name of the highlight part in results
    highlightTag = "em"
    
	# whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false

  # Home page config
  [params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    
	# Home page profile
    [params.home.profile]
      enable = true
      
	  # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      
	  # URL of avatar shown in home page
      avatarURL = ""
      
	  # title shown in home page (HTML format is supported)
      title = ""
      
	  # subtitle shown in home page (HTML format is supported)
      subtitle = ""
      
	  # whether to use typeit animation for subtitle
      typeit = true
      
	  # whether to show social links
      social = true
      
	  # disclaimer (HTML format is supported)
      disclaimer = ""

  # Social config about the author
  [params.social]
    Instagram = "https://www.instagram.com/swingconnectionleipzig/"
    Facebook = "https://www.facebook.com/groups/swingconnection.leipzig"
	Youtubechannel = "https://www.youtube.com/user/swingconnection"
	Email = "info@swingconnection-leipzig.com"
    RSS = true

  # TypeIt config
  [params.typeit]
    
	# typing speed between each step (measured in milliseconds)
    speed = 50
    
	# blinking speed of the cursor (measured in milliseconds)
    cursorSpeed = 1000
    
	# character used for the cursor (HTML format is supported)
    cursorChar = "|"
    
	# cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration = -1

# App icon config
  [params.app]
    
	# optional site title override for the app when added to an iOS home screen or Android launcher
    title = "SwingConnection Leipzig e.V."
    
	# whether to omit favicon resource links
    noFavicon = false
    
	# modern SVG favicon to use in place of older style .png and .ico files
    svgFavicon = ""
    
	# Android browser theme color
    themeColor = "#ffffff"
    
	# Safari mask icon color
    iconColor = "#5bbad5"
    
	# Windows v8-10 tile color
    tileColor = "#da532c"


# Language config
[languages]
  
  [languages.de]
    weight = 1
    languageCode = "de"
    languageName = "German"
    
	[[languages.de.menu.main]]
	  identifier = 'aktuelles'
	  name = 'Aktuelles'
	  url = '/aktuelles/'
	  weight = 1
	
    [[languages.de.menu.main]]
	  identifier = 'tanzkurse'
	  name = 'Tanzkurse'
	  url = '/tanzkurse/'
	  weight = 2

    [[languages.de.menu.main]]
	  identifier = 'veranstaltungen'
	  name = 'Veranstaltungen'
	  url = '/veranstaltungen/'
	  weight = 3

    [[languages.de.menu.main]]
	  identifier = 'calloway'
	  name = 'Tanzstudio'
	  url = '/calloway/'
	  weight = 4
	
    [[languages.de.menu.main]]
	  identifier = 'verein'
	  name = 'Unser Verein'
	  url = '/verein/'
	  weight = 5
	
    [[languages.de.menu.main]]
	  identifier = 'kontakt'
	  name = 'Kontakt & Impressum'
	  url = '/kontakt/'
	  weight = 6
	  
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    
	[[languages.en.menu.main]]
	  identifier = 'aktuelles'
	  name = 'News'
	  url = 'en/news/'
	  weight = 1
	
    [[languages.en.menu.main]]
	  identifier = 'tanzkurse'
	  name = 'Dance classes'
	  url = 'en/classes/'
	  weight = 2

    [[languages.en.menu.main]]
	  identifier = 'veranstaltungen'
	  name = 'Events'
	  url = 'en/events/'
	  weight = 3

    [[languages.en.menu.main]]
	  identifier = 'calloway'
	  name = 'Studio'
	  url = 'en/calloway/'
	  weight = 4
	
    [[languages.en.menu.main]]
	  identifier = 'verein'
	  name = 'Our association'
	  url = 'en/association/'
	  weight = 5
	
    [[languages.en.menu.main]]
	  identifier = 'kontakt'
	  name = 'Contact & Imprint'
	  url = 'en/contact/'
	  weight = 6
  
