baseURL = 'https://hnolzen.github.io/swingconnection/'
languageCode = 'de-de'
title = 'SwingConnection Leipzig e.V.'
theme = 'LoveIt'
enableEmoji = true

[menu]

  [[menu.main]]
	identifier = 'aktuelles'
	name = 'Aktuelles'
	url = '/aktuelles/'
	weight = 1
	
  [[menu.main]]
	identifier = 'tanzkurse'
	name = 'Tanzkurse'
	url = '/tanzkurse/'
	weight = 2

  [[menu.main]]
	identifier = 'veranstaltungen'
	name = 'Veranstaltungen'
	url = '/veranstaltungen/'
	weight = 3

  [[menu.main]]
	identifier = 'calloway'
	name = 'Tanzstudio'
	url = '/calloway/'
	weight = 4
	
  [[menu.main]]
	identifier = 'verein'
	name = 'Unser Verein'
	url = '/verein/'
	weight = 5
	
  [[menu.main]]
	identifier = 'kontakt'
	name = 'Kontakt & Impressum'
	url = '/kontakt/'
	weight = 6

[params]

  defaultTheme = "light"
  
  title = "SwingConnection Leipzig e.V."
  description = "Herzlich Willkommen bei der SwingConnection Leipzig"
  
  images = ["/static/scl_logo.png"]
  
  
  
  
