baseURL = 'http://hnolzen.github.io/'
languageCode = 'de-de'
title = 'SwingConnection Leipzig e.V.'
theme = 'pm'
enableEmoji = true

[menu]

  [[menu.main]]
	identifier = 'aktuelles'
	name = 'Aktuelles'
	url = '/aktuelles/'
	weight = 1
	
  [[menu.main]]
	identifier = 'tanzkurse'
	name = 'Tanzkurse'
	url = '/tanzkurse/'
	weight = 2

  [[menu.main]]
	identifier = 'veranstaltungen'
	name = 'Veranstaltungen'
	url = '/veranstaltungen/'
	weight = 3
	
  [[menu.main]]
	identifier = 'verein'
	name = 'Unser Verein'
	url = '/verein/'
	weight = 4
	
  [[menu.main]]
	identifier = 'kontakt'
	name = 'Kontakt & Impressum'
	url = '/kontakt/'
	weight = 5

