name: Build and Deploy Site

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site with Hugo
        run: hugo --minify

      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./public"
          arguments: --only-4xx --check-favicon --check-html --assume-extension --empty-alt-ignore --disable-external
        continue-on-error: true

      - name: Add a robots.txt to disallow crawling staging
        run: |
          mkdir ~/.buildout
          cat > ./public/robots.txt <<EOF
          User-agent: *
          Disallow: /

          EOF
      - name: Deploy to swingconnection staging
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          local_path: './public/*'
          remote_path: ${{ secrets.SFTP_REMOTE_PATH }}
          sftp_only: true
